### ISSUE TITLE
Passwords not reproducible after selecting a different ruleset and reselecting the original one

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#100]
After restart, a password is not reproducible after temporary selecting a different ruleset ("playing with other rules") and reselecting the original one. With "rule" i mean a different "point" in the matrix.

I found, that a different password is shown.

But even more strange: the first characters are often the same ("Z+ed......") but the **rest** changed when coming back to the original "rules".

**Comment by 607011** [comment]
@Wikinaut Not a bug. It's by design. Really ;-)

You can use "Reset" ("Zurücksetzen") to restore accidentally/experimentally changed settings.
