### ISSUE TITLE
When playing with the rules, and coming back to a certain setting, the first character are often the same

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#101]
But even more strange: the first characters are often the same ("Z+ed......") but the rest changed when coming back to the original "rules".

How to reproduce:
- Start with settings for a domain x. Memorize the original password OP (write it down).
- Now select a different rule, then select the original rule, or different rule
- repeat the previous step
- reselect the original rule

I noticed, that quite often the first 3..4 characters of the password are the **same** as the OP.

**Comment by 607011** [comment]
@Wikinaut I still insist that this is no bug (see #100). The behavior you described is intended.

Brief explanation: Each time you select a different setting in the colored 2D password rule chooser, a new password template is shuffled according to the rules. Shuffling implies some kind of randomness. This randomness results in slightly varying passwords each time you reselect the originally selected setting.

Let's say that the password rules determined by the 2D chooser specify a length of 10 characters and enforces the use of digits, lower-case and upper-case characters, then the base template "naAxxxxxxx" is being generated (_n_ stands for a digit, _a_ for a lower-case character, _A_ for an upper-case character and _x_ for any characters of the selected character sets; see `MainWindow::setTemplateAndUsedCharacters()`)

After shuffling the template may look like "xxxAxaxnxx". The shuffled template is then used to generate the actual password by picking a character from the corresponding set for each template character. The position in that set is determined by the remainder of the division of the password key by the size of the set (see `Password::remixed()`).

**Comment by pinae** [comment]
@Wikinaut Would it be better if the salt is randomized with every change in the strength setting? That would result in completely different passwords with every change.

**Comment by 607011** [comment]
@pinae I also wonder what the critique is all about ;-)

@Wikinaut Are your comments just an expression of disconcertment regarding Qt-SESAM's behavior? Do you want us to classify your report as an error? Or what else do you want us to do?

**Comment by Wikinaut** [comment]
As someone with good knowledge of PRNG I regard it as a security problem with the generator if it creates some (3..4) >same< leading characters.

**Comment by 607011** [comment]
@Wikinaut There's no security problem with this. It only would be if the _same_ leading characters were created with _any_ parameter set. But this isn't the case. E.g. any time you change the salt, a completely different password is being generated. The same is true when changing the domain or user name or the number of iterations.

If you really need a new password for an existing domain, do so by clicking the button left to the generated password. This will shuffle a new salt, giving a totally different password.

It's not recommended to generate a new password for an already existing domain only by varying the password length or choosing another character set through playing with the colored 2D chooser.

**Comment by pinae** [comment]
This issue is not a security problem but a usability issue. If the user expects a completely new password each time she changes the settings then the software should behave in that way.

**Comment by 607011** [comment]
@pinae Agreed.
