### ISSUE TITLE
Feature request: Close Button on the re-enter password window

### ISSUE THREAD

**Issue by pinae** [ola-ct/Qt-SESAM#102]
I often start QtSESAM, create a password use it and forget to close the app. After 5 minutes I am prompted for the masterpassword but I don't want to enter it because I don't need the app at this moment. Most of the time I just want to close QtSESAM. It would really help if there was a button for that.

**Comment by 607011** [comment]
Seconded.

**Comment by 607011** [comment]
Hint to assignee: main window must not lock if parameters are dirty.

**Comment by 607011** [comment]
Fixed with commit e003726008850af40d28cf112df51e17447d8b75
