### ISSUE TITLE
web browser integration

### ISSUE THREAD

**Issue by qw3ry** [ola-ct/Qt-SESAM#109]
Is there anything happening with web browser integration?

I like the philosophy behind Qt-Sesam, but without browser support it's quite useless to me - I'm currently using KeePass2, which replaces my firefox password safe quite well (with PassIFox + KeePassHttp Plugins) and I won't consider switching to Qt-Sesam without any browser integration (opera or chromium would be fine as well, I'm just using mainly firefox at the moment).

I found #81, but did not find any instructions how to get this set up (it did not seem to work out of the box).

I could consider coding a bit myself, but unfortunately my time is limited, so I can't promise anything at the moment.

**Comment by 607011** [comment]
Thanks for your question, @qw3ry 

The 1-click login (#81) is work in progress in a branch. There's a lot of work to do before it can be considered ready for production.

**Comment by 607011** [comment]
To be continued in #110.
