### ISSUE TITLE
Options are not saved

### ISSUE THREAD

**Issue by rramthun** [ola-ct/Qt-SESAM#119]
Both master and beta14 don't save any settings from the Extras -> Options dialogue on my machine, e.g. sync server URL or iterations. The logging messages don't show an attempt to save any data.

Saving passwords works flawlessly though. Compiled against Qt 5.4.2 on Gentoo Linux.

**Comment by 607011** [comment]
Is the bug still present in HEAD (6840a1b12ddddad8db04b5d0dfb4862cbf6ca697)?

If yes, please tell me exactly what you did and what happened? Thanks in advance.

**Comment by rramthun** [comment]
Unfortunately it is.

I compile Qt-SESAM with

```
    git clone git://github.com/ola-ct/Qt-SESAM.git &&
    cd Qt-SESAM &&
    lrelease Qt-SESAM/Qt-SESAM.pro &&
    /usr/lib/qt5/bin/qmake &&
    make &&
    make check
```

Then it is started for the first time, i.e. no configuration files/folders exist yet. After setting the master password, I'm asked by a first start dialogue to change the values for the sync server. I follow this advice and close the dialogue with OK. I open the dialogue via Extras -> Optionen again and all settings are, as I modified them. After closing the whole program, the custom settings are gone and are back to the default values.

I haven't got Qt-SESAM to save any of the preferences from Extras -> Optionen yet, even on subsequent starts after the first one.

**Comment by 607011** [comment]
Got it. The problem occured when the given sync file doesn't yet exist. Should be fixed now. @rramthun Could you please be so kind and give it another try? Thanks in advance.

**Comment by rramthun** [comment]
The problem seems to be fixed with the latest commit. Thanks for your quick response!

**Comment by 607011** [comment]
Thanks for your patience, @rramthun
