### ISSUE TITLE
Options|Misc: Logging is always on

### ISSUE THREAD

**Issue by MarcusRoeckrath** [ola-ct/Qt-SESAM#125]
I disabled logging by deactivating the logging check box leaving the options window with the OK button.

On next start the logging option is ON again.

**Comment by MarcusRoeckrath** [comment]
I did not find code for saving or restoring of logging settings the following procedures in mainwindow.cpp:

saveUiSettings
restoreUiSettings

IMHO this could be the problem.

**Comment by MarcusRoeckrath** [comment]
I fixed it this way (mainwindow.cpp):

Added to the end (directly before the closing bracket of the function) of `MainWindow::saveUiSettings(void)`:
`d->settings.setValue("misc/loggingEnabled", d->optionsDialog->loggingEnabled());`

Added to the end (directly before the closing bracket of the function) of `MainWindow::restoreUiSettings(void)`:
`d->optionsDialog->setLoggingEnabled(d->settings.value("misc/loggingEnabled", true).toBool());`

**Comment by 607011** [comment]
Thanks, @MarcusRoeckrath, that should fix it. Would you like to send me a [pull request](https://help.github.com/articles/using-pull-requests/)?

**Comment by MarcusRoeckrath** [comment]
I had never done such a thing before and do not know much about branches; therefore I had to read the help pages very carefully which will take some time.

I clicked on pull request in the menu but did not realize what I have to do now.

**Comment by 607011** [comment]
Concise info on [How to contribute](https://github.com/ola-ct/Qt-SESAM/wiki/Contribute) is found in the Qt-SESAM wiki, @MarcusRoeckrath – No need to read anything and everything about pull requests.

**Comment by MarcusRoeckrath** [comment]
Sorry, but I wasn't succesfull.

Wether I don't know if I have made all previous steps from the "How to contribute" article in the right way the finishing git push -u origin Issue-125 command failed completely.

This was my first attempt to work with git.

**Comment by MarcusRoeckrath** [comment]
Maybe I was succesfull now.

**Comment by 607011** [comment]
Fixed. Thx @MarcusRoeckrath.
