### ISSUE TITLE
compilation failure on ubuntu 16.04: password.cpp:217:38: error: taking address of temporary [-fpermissive]

### ISSUE THREAD

**Issue by alleehol** [ola-ct/Qt-SESAM#128]
cd libSESAM/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /data/allee/Sources/qt-sesam/Qt-SESAM/libSESAM/libSESAM.pro -o Makefile ) && make -f Makefile 
make[1]: Verzeichnis „/data/allee/Sources/qt-sesam/Qt-SESAM/libSESAM“ wird betreten
g++ -c -m64 -pipe -std=c++11 -O2 -fPIC -w -std=c++0x -D_REENTRANT -DCRYPTOPP_DISABLE_X86ASM -DCRYPTOPP_DISABLE_SSSE3 -DPLATFORM=64 -DQTSESAM_VERSION=\"2.1.0-BETA15\" -DQT_NO_DEBUG -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I3rdparty/bigint -I3rdparty/cryptopp -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o password.o password.cpp
password.cpp: In member function ‘SecureString Password::remix()’:
password.cpp:217:38: error: taking address of temporary [-fpermissive]
       charSet = &TemplateCharacters[m];
                                      ^
Makefile:3845: die Regel für Ziel „password.o“ scheiterte

$ g++ --version
g++ (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
...

**Comment by gu471** [comment]
Hab das gleiche Problem auf einem frisch installiertem Ubuntu 16.

**Comment by diffusae** [comment]
Ja, dies sieht bei mir mit Ubuntu 14.04 genauso aus. Vor ein paar Tagen konnte alles noch problemlos kompiliert werden. Leider habe ich die alten Quellen gleich gelöscht. ;-(

**Comment by 607011** [comment]
Resolved by commits 704fcf1 and e342751.
