### ISSUE TITLE
Build a Mac OS X binary

### ISSUE THREAD

**Issue by 607011** [ola-ct/Qt-SESAM#17]

**Comment by 607011** [comment]
App and both libraries compile on Mac OS X 10.10.2 (14C1514) w/ Qt 5.5.0 :-)

UnitTests fail to compile with the following message:

```
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks'
ld: framework not found XCTest
```

Does anyone know how to solve this problem?

**Comment by deets** [comment]
Works for me, Xcode 6.4, OS X 10.10.3, Qt 5.5

**Comment by 607011** [comment]
First DMG is ready for testing: https://github.com/ola-ct/Qt-SESAM/releases/tag/v2.0.6
