### ISSUE TITLE
HashMaster/main.cpp does not compile on Linux

### ISSUE THREAD

**Issue by hendwolt** [ola-ct/Qt-SESAM#32]
When compiling on openSUSE 13.2 I get these error messages:

make[1]: Entering directory '/daten/hendriks_dateien/projekte/ctsesam/Qt-SESAM-x86x64-dist/HashMaster'
g++ -c -pipe -O2 -w -std=c++0x -fPIC -DCRYPTOPP_DISABLE_X86ASM -DCRYPTOPP_DISABLE_SSSE3 -DQTSESAM_VERSION=\"2.0.3\" -I. -I../cryptopp -I/usr/lib64/qt5/mkspecs/linux-g++ -o main.o main.cpp
main.cpp: In function ‘int main(int, char*_)’:
main.cpp:147:3: error: ‘WIN32_FIND_DATAA’ was not declared in this scope
   WIN32_FIND_DATAA findData;
   ^
main.cpp:147:20: error: expected ‘;’ before ‘findData’
   WIN32_FIND_DATAA findData;
                    ^
main.cpp:148:3: error: ‘HANDLE’ was not declared in this scope
   HANDLE ff = FindFirstFileA(fname.c_str(), &findData);
   ^
main.cpp:148:10: error: expected ‘;’ before ‘ff’
   HANDLE ff = FindFirstFileA(fname.c_str(), &findData);
          ^
main.cpp:149:7: error: ‘ff’ was not declared in this scope
   if (ff != INVALID_HANDLE_VALUE) {
       ^
main.cpp:149:13: error: ‘INVALID_HANDLE_VALUE’ was not declared in this scope
   if (ff != INVALID_HANDLE_VALUE) {
             ^
main.cpp:150:9: error: ‘findData’ was not declared in this scope
     if (findData.cFileName != nullptr) {
         ^
main.cpp:153:31: error: ‘findData’ was not declared in this scope
     while (FindNextFileA(ff, &findData)) {
                               ^
main.cpp:153:39: error: ‘FindNextFileA’ was not declared in this scope
     while (FindNextFileA(ff, &findData)) {
                                       ^
Makefile:377: recipe for target 'main.o' failed
make[1]: *_\* [main.o] Error 1

It happens with current master sources too.

**Comment by 607011** [comment]
The error you got was transitional. Please `make clean`, `git pull`, `qmake` and `make` again.

FYI: HashMaster is not supposed to compile under Linux ;-) It's an auxiliary program I use to build the installer on Windows.
