### ISSUE TITLE
Separate master password from domain password

### ISSUE THREAD

**Issue by digulla** [ola-ct/Qt-SESAM#34]
The code generates the domain password like so:

```
const QByteArray &pwd =
  d->domainSettings.domainName.toUtf8() +
  d->domainSettings.userName.toUtf8() +
  masterPassword;
```

This is great from a security perspective but bad for usability: If I change my master password, I have to reset all passwords for all web sites.

Since the domain password already has a salt, my feeling is that including the master password doesn't add much to security.

**Comment by 607011** [comment]
The variable is called `masterPassword` but actually is a key which is encrypted with the master password. This allows you to change your master password without the need to reconfigure all of your domains.

So there's no need to fix the code.

**Comment by digulla** [comment]
Can you refactor the variable name? `masterKey` would be much less confusing.

**Comment by pinae** [comment]
I agree. `masterKey` would be a better name.

**Comment by 607011** [comment]
Check.

**Comment by 607011** [comment]
Already done in 90ba98b9d0fe4cbbb22d2b9db1fd5962c5b9b0e0.
