### ISSUE TITLE
Geometry not restored from .ini file

### ISSUE THREAD

**Issue by stefanb2** [ola-ct/Qt-SESAM#42]
I see in my .ini file:

```
[mainwindow]
...
geometry=@Rect(612 115 866 671)
```

but these values are ignored when main window opens after restart, i.e. main window always pops up with the same default size.

OS: Fedora 22 x86_64, QT 5.5, KF5 5.13, Plasma 5.3

**Comment by 607011** [comment]
Resolved with commit 39d46ee798169c538d816295fa46418bfcd86303.
