### ISSUE TITLE
Linux: support for kwallet/gnome-keyring

### ISSUE THREAD

**Issue by stefanb2** [ola-ct/Qt-SESAM#43]
I know this might be controversial, but it might be nicer for end users if the master password is stored and retrieved from default session secure storage. Under KDE this would be "kwallet5", under GNOME it would be "gnome-keyring".

AFAIU they both offer the same DBUS interface, so IMHO no separate implementation would be required.

**Comment by 607011** [comment]
I think it's a neat idea to ease the process of storing and retrieving passwords as long as the user is aware of all its implications on security.

**Comment by 607011** [comment]
[Building and Using the Secret Service Java API](http://www.codeguru.com/java/article.php/c19947/Building-and-Using-the-Secret-Service-Java-API.htm#page-4)

[Secret Service API Draft](http://standards.freedesktop.org/secret-service/)

**Comment by 607011** [comment]
Integrated [QKeychain lib](https://github.com/frankosterfeld/qtkeychain) on [branch QKeychain-Dev](https://github.com/ola-ct/Qt-SESAM/tree/QKeychain-Dev). So a forthcoming release of Qt-SESAM will more than likely support automatic fill in of the master password on Linux, Windows and OS X.

**Comment by 607011** [comment]
Decided not to implement this feature because it would downgrade the overall security of the application.
