### ISSUE TITLE
Linux: duplicate "Quit" entry in system tray icon menu

### ISSUE THREAD

**Issue by stefanb2** [ola-ct/Qt-SESAM#44]
On my Fedora 22 box with KDE Plasma 5 the system tray icon menu looks like this

![Uploading QtSESAM-tray-menu-KDEPlasma.png…]()

As you can see there is a duplicate "Quit" entry at the end. This is not generated by Qt-SESAM, but automatically by the system (it's translation changes when I switch languages).

I'm not sure how to solve this. If this is the case for every Linux user, but not Windows user, then I would suggest to flag the generation of the "Quit" entry with #ifdef WIN32 in the code.

**Comment by stefanb2** [comment]
The one generated by the system (the lower entry with icon) quits the program correctly. But it causes issue #45.

The one generated by QT-SESAM (the upper entry without icon) only closes the main window.

**Comment by stefanb2** [comment]
As far as I can tell from the source code, the main menu entry `File -> Exit` and the system tray icon menu entry `Quit` are connected to the main window slot `close()`. I.e. they only close the main window, but do not exit the application.

The system generated entry on the system tray icon menu causes this dialog:

![Uploading QtSESAM-tray-menu-Exit-Dialog.png…]()

which I can't find in the source code. So I assume this is a "force application" dialog from the system.

IMHO a real "exit" is missing in the Qt-SESAM code

**Comment by stefanb2** [comment]
ah damn... wrong button. This is NOT closed :-(

**Comment by stefanb2** [comment]
OK, somehow the PNG uploads got lost. Trying again:

![qtsesam-tray-menu-exit-dialog](https://cloud.githubusercontent.com/assets/9963933/9901712/f1ad61c2-5c71-11e5-9ca0-15a998134942.png)

![qtsesam-tray-menu-kdeplasma](https://cloud.githubusercontent.com/assets/9963933/9901693/d5e558d2-5c71-11e5-8e17-3a0cc55bd1ca.png)

**Comment by 607011** [comment]
If `close()` is called on the `MainWindow` the main loop exits, thus ending the application. That's the theory and works on Windows in practice. Regarding the Qt docs this is the desired behavior of `close()` and should be the same on other platforms. _Should_  …

**Comment by stefanb2** [comment]
I checked the documentation: your mainwindow code looks correct. Except maybe the `QMainWindow::closeEvent()` calls.

I even connected the `exit` with the `closeAllWindows` slot on `qApp` and it still doesn't work.

So my assumption is that the problem is in `QApplication`, not your main window code. I.e. the application doesn't exit when the last window is closed.

**Comment by 607011** [comment]
Regarding the extra "Quit" tray item: It doesn't appear on every Linux desktop. So it leads to nothing to `#ifdef WIN32` the code section that inserts the "Quit" action :-(

**Comment by 607011** [comment]
Obviously some Linux desktops add a quit button by themselves. Won't do anything about it. Thus closing this issue.
