### ISSUE TITLE
[Suggestion] Add an option to clear the Master password

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#51]
In the case that you forgot the MP, there appears to be no clean (programmatic) way to reset it, because the change option requires the old password. 

I suggest to add an additional option, with an additional prompt, to clear it.

**Comment by 607011** [comment]
You need the old password to decrypt your settings.

**Comment by Wikinaut** [comment]
@ola-ct of course, that is clear.
But, for example, when I play and test the program, I use a Wegwerf-Passwort. How to clear it from the "installed" instance to have fresh restart?

**Comment by 607011** [comment]
@Wikinaut s. [FAQ](https://github.com/ola-ct/Qt-SESAM/wiki/FAQ-%5Bde%5D)

**Comment by Wikinaut** [comment]
Na, okay.

**Comment by 607011** [comment]
Pro-Tipp, @Wikinaut: For testing purposes use the portable version of Qt-SESAM which stores all its settings in a subdirectory of the working directory. If you're done with testing, just delete the directory in which you unzipped Qt-SESAM.

**Comment by Wikinaut** [comment]
@ola-ct I am interested in testing the bleeding edge, i.e. latest version per "git pull". Thanks for the portable version tip, but seems to be different than the mere "git pull" version.
