### ISSUE TITLE
Typing in the Domain field does not update the password

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#54]
When I start the program and enter characters in the top field(s) - from which I think the password should be generated - the password is not updated.

The process should either be "it generates the password as you type (or on the event that the input has changed)" or "clear the password field while a new password is being generated".

Currently, it does not work in one of the ways. Or, it's a bug (I don't know but wanted to tell you my observation).
#### in addition

Perhaps we can add a small "*)" after the field name strings ("Domain" etc.) from which the password depends.

**Comment by 607011** [comment]
Good point. I'm going to look after it.

**Comment by Wikinaut** [comment]
just as a remark: when i) changing the character set, or ii) when changing the password length, this already works: the password is generated on-the-fly, as you type.

**Comment by 607011** [comment]
I chose to implement a different solution: Any invalid value in the domain combobox clears the contents of all other fields.
