### ISSUE TITLE
Decryption error on program start (correct password entered) also in case of sync file reading error

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#57]
When starting the program and problems occur while reading the sync file, the message of the 
Decryption error window on program start (correct password entered, but the window tries to explain a password problem) is wrong.

In this case, the error message should tell the user that there is an access problem with the sync file.
Not a password mismatch problem-

**Comment by 607011** [comment]
Which message do you see but don't want to?

**Comment by Wikinaut** [comment]
Current message is

```
An error occured while decrypting your data
(#4, StreamTransformationFilter: invalid PKCS #7 block padding found).

Maybe you entered a wrong password. Please enter the correct password!
```

The program flow appears to be:
1. enter password
2. fetch file

and the message above is for both cases (password wrong, or file not readable).

Better you change the program flow on start
1. fetch file
2. enter password
and present a single corresponding error message for each of the cases.

Here's a proposal for an improved message for the current version

```
An error occured while trying to decrypt your data
(#4, StreamTransformationFilter: invalid PKCS #7 block padding found).

Either the password (parameter) fiie is not present or readable.
Check, whether the sync file is accessible and readable.

Or you may have entered a wrong password. 
Please enter the correct password!
```

**Comment by 607011** [comment]
Note to self: Maybe I forgot to check if the sync file is present and readable before trying to decode it.

**Comment by 607011** [comment]
No, I haven't. See lines [1259](https://github.com/ola-ct/Qt-SESAM/blob/master/Qt-SESAM/mainwindow.cpp#L1259) and [1274](https://github.com/ola-ct/Qt-SESAM/blob/master/Qt-SESAM/mainwindow.cpp#L1274) in mainwindow.cpp. ***_scratchinghead**_*

**Comment by Wikinaut** [comment]
Closing this "invalid/cannot reproduce" But https://github.com/ola-ct/Qt-SESAM/issues/56 is still valid.
