### ISSUE TITLE
When starting the program, empty main screen is shown and allows to enter a domain name. Instead, "New domain" dialog should pop up.

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#62]
I noticed the following problem.

When you start the program (for the first time, or a further time), on my computer it shows the empty main window, which allows me to type something into the Domain field (which I later found, is the incorrect place, as explained as follows).

However, all other fields are empty, so as the "used character" set field, for example, which does not make sense. Later I found, that the program has a "New domain..." function. 

This "New domain" window should - in my view - automatically start when
- program is initially started
- user tries to type a character into the empty domain field of the main window.

**Comment by Wikinaut** [comment]
This is different from issue #60

**Comment by 607011** [comment]
I know, I know, I know ;-) This is an issue I tinkered around a couple of times but came to no satisfying solution.

Commit 013cee5eb3f5fc4b2380e3d5647520bb333f7919 now triggers the new domain wizard when leaving the domain field after the user filled something in there.

It's not perfect but a first step to fulfill your request.

**Comment by Wikinaut** [comment]
off-topic question; when upgrading with "git pull", is "git pull;make" sufficient, or do you suggest the full installation procedure?

**Comment by 607011** [comment]
After `git pull` you should always `qmake`.

If something weird happens while building with `make` execute

```
make clean
find . -type f -name Makefile -exec rm {} \;
```

before `qmake`.

**Comment by 607011** [comment]
Side note: I've implemented the new domain wizard so that the user does not have to see rarely used UI elements like the character set buttons (ABC…, abc…, 0123…).

**Comment by Wikinaut** [comment]
s/qmake/qmake-qt5/

**Comment by 607011** [comment]
`qmake-qt5` for the openSUSE and Fedora guys, `qmake` for Debians.

**Comment by 607011** [comment]
Resolved #62, #65 and #54 in one go.
