### ISSUE TITLE
Add grey text "may be empty" to the "URL" input field

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#63]
<img src=http://i.imgur.com/kz4lBAW.png>

**Comment by Wikinaut** [comment]
@ola-ct PRO-TIP: Do you know how to include image/s from imgur et al.?

add code like

```
<img src="http://i.imgur.com/kz4lBAW.png">
```

**Comment by 607011** [comment]
Pro-Tipp No. 2: Attach images by dragging & dropping, selecting them, or pasting from the clipboard ;-)

**Comment by 607011** [comment]
Resolved by commit 6256fa639c4b065d4a479ba08f05131a8d4faa44
