### ISSUE TITLE
Extra > Options... > Misc: add description or tooltip for "Password dictionary file" input field

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#64]
There's no explanation, what the function of such a file is.

Suggestion: add a text (preferred), or add a tooltip.

Note to self: Wenn ich das Programm verstanden habe, werde ich PRs einreichen.

**Comment by 607011** [comment]
This will all be mentioned in the User's Manual.

Sometime.

ASAP. 

We'll see …
