### ISSUE TITLE
Opportunity for more efficient encrypt and decrypt

### ISSUE THREAD

**Issue by noloader** [ola-ct/Qt-SESAM#67]
Looking at https://github.com/ola-ct/Qt-SESAM/blob/master/libSESAM/crypter.cpp#L139, this might be a little more efficient because it saves you from copying the `QByteArray` into the intermediate `std::string`:

```
QByteArray Crypter::encrypt(const SecureByteArray &key, const SecureByteArray &IV, const QByteArray &plain, CryptoPP::StreamTransformationFilter::BlockPaddingScheme padding)
{
  CryptoPP::CBC_Mode<CryptoPP::AES>::Encryption enc;
  enc.SetKeyWithIV(reinterpret_cast<const byte*>(key.constData()), key.size(), reinterpret_cast<const byte*>(IV.constData()));
  CryptoPP::ArraySource as(
        plain.constData(), plain.size(),
        true,
        new CryptoPP::StreamTransformationFilter(
          enc,
          new CryptoPP::StringSink(sCipher),
          padding
          )
        );
  Q_UNUSED(s); // just to please the compiler
  return QByteArray(sCipher.c_str(), sCipher.length());
}
```

You can probably do similar when using the `ArraySink`. The trick is, you need to presize the array in advance. Then, once encryption completes, you can resize it as required. The size of the cipher text depends upon the padding scheme.

**Comment by 607011** [comment]
Thanks. I like the idea not to use the counterintuitive `std::string` in favor of a `QByteArray`. (See preliminary commit 1fa1888520004fdf5ab8022685cc46533687c26f.)
