### ISSUE TITLE
Passwort settings: cannot select "Simple". Only "Expert" setting.

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#83]
"Simple" is greyed out, not selectable.

**Comment by 607011** [comment]
"Simple" is only selectable for already existing domains.

The "Expert" method is the preferred one. I should probably rename that tab … Suggestions?

**Comment by Wikinaut** [comment]
but what if I want to have my own character set back? (e.g. 0123456789abcdef+-/$ )

**Comment by 607011** [comment]
This won't work without the "simple" tab. It's a trade-off between usability (i.e. UI clearness) and the number of occasions in which you are forced to use character sets other than _digits_, _lowercase_, _uppercase_, _digits/lowercase_, _lowercase/uppercase_, _digits/lowercase/uppercase_ or _digits/lowercase/uppercase/special_.

**Comment by Wikinaut** [comment]
As said: I want to have my own set/s of characters back, per domain.

**Comment by 607011** [comment]
As I said: It's a trade-off. And we decided to hide the "simple" tab from the user for newly created domain settings.

Feel free to fork Qt-SESAM and remove all lines with

```
ui->tabWidgetVersions->setTabEnabled(TabSimple, false);
```

in Qt-SESAM/mainwindow.cpp to restore the desired behavior.

Then send a pull-request and we'll probably merge it.

**Comment by 607011** [comment]
We're going to sit upon your suggestion on Monday, @Wikinaut.

**Comment by 607011** [comment]
@Wikinaut We're not going to roll back to "Simple", but there will be another solution that suits your needs.
