### ISSUE TITLE
No password displayed after sync

### ISSUE THREAD

**Issue by pinae** [ola-ct/Qt-SESAM#91]
After syncing settings with a server no password gets displayed. This especially occurs after starting QtSESAM if sync on start is activated. If the field is empty you can not copy the password to the clipboard.

There is a workaround: select another domain and the desired domain again.

![qtsesam_nopassword](https://cloud.githubusercontent.com/assets/1160927/10935663/c9e8e188-82e7-11e5-85a1-9aed88a190c7.png)

**Comment by Wikinaut** [comment]
same problem here with b927b356501c3b95e34029515060b6de0a2fdeb0

**Comment by 607011** [comment]
Reproducible with "sync to server", "sync to file", or both enabled.

**Comment by 607011** [comment]
Happens only directly after start, i.e. when no domain has been selected yet from the combo box.

**Comment by 607011** [comment]
Resolved with commit e01e12cfc50e5cc31c9eb4d8f5fdc3665b9df6e7.

Solution as a reminder: `QWidget::setEnabled(true)` will have no effect if a parent widget is disabled.
