### ISSUE TITLE
Delete backups after master password has been changed

### ISSUE THREAD

**Issue by 607011** [ola-ct/Qt-SESAM#94]

**Comment by pinae** [comment]
There should be an option for this. The option could be enabled by default.

If you decide against this option: The documentation should make very clear that the backups are deleted on password change. So users can backup the backups to keep them.

**Comment by 607011** [comment]
:+1: @pinae

**Comment by 607011** [comment]
There should also be an option to automatically delete backup files older than x days.

**Comment by 607011** [comment]
Fixed (see commit 68e680d4bd0d0bb4c01c2898d8c6a201f7551fea).
