### ISSUE TITLE
[Linux] Choose another name or folder for lock file

### ISSUE THREAD

**Issue by 607011** [ola-ct/Qt-SESAM#98]
Currently the lock file is stored as "qt-sesam.lck" in a folder returned by `QStandardPaths::writableLocation(QStandardPaths::TempLocation)` which typically is /tmp under Linux. In multiuser environments this would lead to "another instance is already running" error message if another user already has Qt-SESAM running.

Solution 1: Choose a temp folder below the user's home directory.

Solution 2: Choose another name for the lock file, e.g. by adding the user's id to it.

**Comment by pinae** [comment]
Truecrypt uses `~/.Truecrypt-lock-username`. Maybe this is suitable?

**Comment by 607011** [comment]
:+1: @pinae Yes. Something like that.

**Comment by 607011** [comment]
Fixed with commit 3e26a73ebd7b885621e21a191cfc6ca2283a9a8f
